name: tajammul_customer_app
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^2.0.0
  hexcolor: ^2.0.3
  country_code_picker: ^2.0.2
  otp_text_field: ^1.1.1
  flutter_switch: ^0.3.2
  date_time_picker: ^2.1.0
  flutter_localizations:
    sdk: flutter
  carousel_slider: ^4.0.0
  smooth_page_indicator: ^1.0.0+2
  graphql_flutter: ^5.0.0
  change_app_package_name: ^1.0.0
  fluttertoast: ^8.0.8
  shared_preferences: ^2.0.12
  http: ^0.13.4
  flutter_svg: ^1.0.3
  flutter_svg_provider: ^1.0.1
  google_maps_flutter: ^2.1.1
  geocoding: ^2.0.2
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.6
  sms_autofill: ^2.2.0
  pinput: ^1.2.2
  intl_phone_number_input: ^0.7.0+2
  http_parser: ^4.0.0
  dotted_border: ^2.0.0+2
  flutter_keyboard_visibility: ^5.2.0
  firebase_messaging: ^11.2.6
  provider: ^6.0.2
  lazy_load_scrollview: ^1.3.0
  location: ^4.3.0
  intl:
  syncfusion_flutter_datepicker:
  expandable_bottom_sheet: ^1.1.1+1
  flutter_local_notifications: ^9.5.3+1
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  path_provider:
  cached_network_image:
  image_picker: ^0.8.5+3
  flutter_countdown_timer: ^4.1.0
  connectivity_plus: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^1.0.0
  build_runner: ^2.1.11
  hive_generator: ^1.1.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/Icons/appLauncherIcon.png"

flutter:

  uses-material-design: true

  fonts:
    - family: Nexa
      fonts:
        - asset: assets/fonts/Nexa-Bold.ttf
        - asset: assets/fonts/Nexa-Light.ttf
        - asset: assets/fonts/Nexa-Regular.ttf


  assets:
    - assets/Icons/
    - assets/Images/


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
