const String USER_TYPE_ADMIN = "ADMIN";
const String USER_TYPE_CUSTOMER = "CUSTOMER";
const String USER_TYPE_BUSINESS_ADMIN = "BUSINESS-ADMIN";
const String USER_TYPE_BUSINESS_USER = "BUSINESS-USER";

//ROLES
const String BUSINESS_TYPE_SERVICE = "SERVICE";
const String BUSINESS_TYPE_PRODUCT = "PRODUCT";

//STATUS
const String STATUS_ACTIVE = "ACTIVE";
const String STATUS_INACTIVE = "INACTIVE";
const String STATUS_SHOP_CLOSED = "SHOP_CLOSED";

//FOR ORDER
const String STATUS_ORDER_IN_PENDING = "PENDING";
const String STATUS_ORDER_IN_PROGRESS = "IN-PROGRESS";
const String STATUS_ORDER_COMPLETED = "COMPLETED";
const String STATUS_ORDER_REJECTED = "REJECTED";

//Order types
const String ORDER_TYPE_POS = "POS";
const String ORDER_TYPE_ONLINE = "ONLINE";

//PRODUCT-STATUS
const String STATUS_PRODUCT_AVAILABLE = "AVAILABLE";
const String STATUS_PRODUCT_UNAVAILABLE = "UN-AVAILABLE";
const String STATUS_PRODUCT_OUT_OF_STOCK = "OUT-OF-STOCK";
const String STATUS_PRODUCT_INVALID_QUANTITY = "INVALID_QUANTITY";
const String STATUS_PRODUCT_PRICE_VALUE_CHANGED = "PRICE_CHANGED";

//ADDRESS TYPES
const String USER_CURRENT_ADDRESS = "CURRENT";
const String USER_ADDIOTIONAL_ADDRESS = "ADDIOTIONAL";